name: Avytage
favicon: null
layout_spectrum: 0.00302
typography_spectrum: 0.3868440603837371
title: Experience The Spirit of Europe´s Luxury Country Life Style
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0e2d7'
    - '#96adcf'
    - '#000000'
    - '#3f3b2f'
    - '#9a0000'
  brandStrength: 0.7562310365028679
  lightness: 0.8537407172843814
  saturation: 0.9463939594570547
  rhythmicContrast: 0.47736834455281496
purpose: []
